# -*- coding: utf-8 -*-
"""Analyzing Simulated Sales Performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YzwEh5-UdM8DXK61w20Tng5tt2SQ08K9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(42)

months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

regions = ["North", "South", "East", "West"]

data = []

for _ in range(120):  # at least 100 rows
    month = np.random.choice(months)
    region = np.random.choice(regions)
    units_sold = np.random.randint(20, 200)
    price = np.random.uniform(15, 60)
    revenue = round(units_sold * price, 2)

    data.append([month, region, units_sold, revenue])

    df = pd.DataFrame(
    data,
    columns=["Month", "Region", "Units Sold", "Revenue"]
)

print("First 5 rows of the dataset:")
print(df.head())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDescriptive Statistics:")
print(df[["Units Sold", "Revenue"]].describe())

plt.figure(figsize=(8, 5))
sns.histplot(df["Revenue"], bins=15, kde=True)
plt.title("Distribution of Revenue")
plt.xlabel("Revenue")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8, 5))
sns.barplot(
    x="Region",
    y="Units Sold",
    data=df,
    estimator=np.mean
)
plt.title("Average Units Sold by Region")
plt.xlabel("Region")
plt.ylabel("Average Units Sold")
plt.show()

